# Generated by Django 5.1.2 on 2024-11-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_discount_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.CharField(choices=[('latest', 'Latest'), ('special', 'Special'), ('featured', 'Featured')], default='latest', max_length=100),
        ),
    ]
