# Generated by Django 5.1.2 on 2024-11-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_productgallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
