# Generated by Django 5.1.2 on 2024-11-12 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='agree_to_terms',
            field=models.BooleanField(default=False),
        ),
    ]
