# Generated by Django 5.1.2 on 2024-11-18 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaillog',
            options={'verbose_name_plural': 'Send Email To Users'},
        ),
    ]
